# Generated by Django 5.2.9 on 2025-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiquesglobales',
            name='jours_total_possibles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistiquesglobales',
            name='total_jours_travailles',
            field=models.IntegerField(default=0),
        ),
    ]
