# Generated by Django 5.2.6 on 2025-09-12 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departement",
            name="nbr_employe",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pointage",
            name="date_pointage",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name="pointage",
            unique_together={("employe", "date_pointage")},
        ),
    ]
