# Generated by Django 5.2.6 on 2025-09-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_departement_nbr_employe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conge",
            name="motif_refus",
            field=models.TextField(blank=True, null=True),
        ),
    ]
